version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  backend:
    image: node:latest
    container_name: backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mydatabase
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
  frontend:
    image: node:latest
    container_name: frontend
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run serve
    ports:
      - "8080:8080"
